### ISSUE TITLE
How to get private key?

### ISSUE THREAD

**Issue by hongkongkiwi** [OJFord/terraform-provider-wireguard#1]
Hi there,

I would like to use this plugin to generate a private key and save it to a file.

I couldn't quite figure out how to do this as private key is not exported from the module.

Is there something I'm missing?

**Comment by OJFord** [comment]
Hi, the example (modulo that it doesn't have a `versions.tf` for terraform v0.13, I'll correct that in a sec) seems to work as you expect for me:

```
terraform-provider-wireguard(master|…)>terraform apply examples/asymmetric_key/

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # wireguard_asymmetric_key.example will be created
  + resource "wireguard_asymmetric_key" "example" {
      + id          = (known after apply)
      + private_key = (sensitive value)
      + public_key  = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

wireguard_asymmetric_key.example: Creating...
wireguard_asymmetric_key.example: Creation complete after 0s [id=lYUkV8tfAL+n3RuEJ+BwZkVu/8gKQVPFHbTi0MbJLT0=]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

wg_public_key = lYUkV8tfAL+n3RuEJ+BwZkVu/8gKQVPFHbTi0MbJLT0=

terraform-provider-wireguard(master|…)>terraform console examples/asymmetric_key/
> wireguard_asymmetric_key.example
{
  "id" = "lYUkV8tfAL+n3RuEJ+BwZkVu/8gKQVPFHbTi0MbJLT0="
  "private_key" = "MIS8zN1g/I4lcUxqNT5/MVIlBoS1OfmSqzvnmvATKFI="
  "public_key" = "lYUkV8tfAL+n3RuEJ+BwZkVu/8gKQVPFHbTi0MbJLT0="
}
> wireguard_asymmetric_key.example.private_key
MIS8zN1g/I4lcUxqNT5/MVIlBoS1OfmSqzvnmvATKFI=
>
```

Do you see the same result for the example? (Different keys of course.) Is there an error when you use it in your actual use case, or the `private_key` is just blank? `null`?

**Comment by OJFord** [comment]
Ah - I see the confusion, in the docs I've written 'the following attributes are exported: public_key'; `private_key` is not mentioned because it's an optional argument, generated if not given, and it is indeed exported either way.

Hashicorp's own providers use the phrase 'in addition to the arguments above the following attributes are exported'; that makes this clearer, I'll switch to that.

Thanks.
