### ISSUE TITLE
Ability to import a `wireguard_asymmetric_key` & `wireguard_preshared_key`

### ISSUE THREAD

**Issue by leonsmith** [OJFord/terraform-provider-wireguard#11]
I know you can target apply & manually adjust the state file to achieve the same thing but it would be nice if you could import a pre-existing `wireguard_asymmetric_key` or `wireguard_preshared_key`

**Comment by leonsmith** [comment]
Might have a go at implementing it myself this week in my spare time 👍

**Comment by OJFord** [comment]
Thank you, yes, I've definitely intended to do this, PR more than welcome but no pressure, I will get to it otherwise.

**Comment by fllaca** [comment]
hi @leonsmith @OJFord ! I implemented this feature in https://github.com/OJFord/terraform-provider-wireguard/pull/38 , please have a look :pray: . 

Thanks for this project!
