### ISSUE TITLE
`wireguard_config_document` writes incorrect DNS setting

### ISSUE THREAD

**Issue by dutch** [OJFord/terraform-provider-wireguard#2]
When using the `wireguard_config_document` property `dns`, it writes the list of IPs separated by commas but with an extra comma at the end, which is incorrect syntax and breaks the config (i.e. it can't be loaded).

**Comment by OJFord** [comment]
Thanks for the report, will look to address it shortly!

**Comment by dutch** [comment]
Whew, thanks for the prompt fix & release :)
