### ISSUE TITLE
plugin signature registration with opentofu

### ISSUE THREAD

**Issue by nejec** [OJFord/terraform-provider-wireguard#35]
I somehow came across an edge case, where the references in `terraform.state` file point to `registry.opentofu.org` and since `terraform` is harsh on checking the GPG signatures, I am getting this error

```
╷
│ Error: Failed to install provider
│
│ Error while installing registry.opentofu.org/ojford/wireguard v0.2.2:
│ authentication signature from unknown issuer
╵
```

Can you add the GPG public key to `registry.opentofu.org` as well? The process is described [here](https://github.com/opentofu/registry/?tab=readme-ov-file) which will guide you to submit your GPG key to [opentofu registry](https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+).

Thank you in advance.

**Comment by OJFord** [comment]
opentofu/registry#562

**Comment by OJFord** [comment]
Thanks again for bringing this to my attention @nejec, done & merged, apparently should take effect within the next couple of hours.
