### ISSUE TITLE
pre-shared key support

### ISSUE THREAD

**Issue by odise** [OJFord/terraform-provider-wireguard#6]
Thanks for the wireguard provider. I currently seeking for pre-shared key support. As far as I see it would be a call of `wgtypes.GenerateKey()`. I just wonder whether to add it to the `resourceWireguardAsymmetricKey` resource or put it separately. @OJFord WDYT?

**Comment by OJFord** [comment]
Hi! Thanks for your interest. I always intended to support it, just haven't got around to it - I'd be glad to review a PR.

Quickly reviewing now, I think my `wireguard_asymmetric_key` name came from a misunderstanding of the PSK option in WireGuard - it's an _additional_ layer, not an alternative. If I named that today I would probably choose `wireguard_key` or `wireguard_keypair` say.

That to say, I think an optional attribute `psk` or `preshared_key` on the existing resource would be the most logical way to go.

If the provider is to _generate_ the key that can then be shared though, I would suggest that that should be its own resource, in order that it can have a lifecycle independent of the key pair it's (currently) attached to, which logically it does.

i.e. if you generated and used the PSK with this provider, it could look something like:
```hcl
resource "wireguard_preshared_key" "my_psk" {}

resource "wireguard_asymmetric_key" "my_keypair" {
  psk = wireguard_preshared_key.my_psk.key
}
```

**Comment by odise** [comment]
@OJFord Please have a look at #7 and tell me what you think.
